DROP PROCEDURE PROC_SECTION_INSERT
GO
CREATE PROCEDURE PROC_SECTION_INSERT(@SECTION_NO INT,@SECTION_NAME VARCHAR(50))
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM SECTION WHERE SECTION_NO = @SECTION_NO)
	BEGIN 
		UPDATE SECTION SET SECTION_NAME=@SECTION_NAME WHERE SECTION_NO = @SECTION_NO
	END
	ELSE
	BEGIN
		INSERT INTO SECTION
		SELECT @SECTION_NO,@SECTION_NAME
	END
END
GO
DROP PROCEDURE PROC_TEACHER_INSERT
GO
CREATE PROCEDURE PROC_TEACHER_INSERT(@TEACHER_ID_NO VARCHAR(11),@NAME_SURNAME VARCHAR(50),@BIRTHDAY DATE,@EMAIL VARCHAR(20),@ZOOM_EMAIL VARCHAR(20),@ADDRES VARCHAR(250))
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM TEACHER WHERE TEACHER_ID_NO = @TEACHER_ID_NO)
	BEGIN 
		UPDATE TEACHER SET NAME_SURNAME=@NAME_SURNAME,BIRTHDAY=@BIRTHDAY,EMAIL=@EMAIL,ZOOM_EMAIL=@ZOOM_EMAIL,ADDRES=@ADDRES WHERE TEACHER_ID_NO = @TEACHER_ID_NO
	END
	ELSE
	BEGIN
		INSERT INTO TEACHER
		SELECT @TEACHER_ID_NO,@NAME_SURNAME,@BIRTHDAY,@EMAIL,@ZOOM_EMAIL,@ADDRES
	END
END
GO
DROP PROCEDURE PROC_TEACHER_SECTION_INSERT
GO
CREATE PROCEDURE PROC_TEACHER_SECTION_INSERT(@REC_NO INT,@TEACHER_ID_NO VARCHAR(11),@SECTION_NO INT)
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM TEACHER_SECTION WHERE REC_NO = @REC_NO)
	BEGIN 
		UPDATE TEACHER_SECTION SET TEACHER_ID_NO=@TEACHER_ID_NO,SECTION_NO=@SECTION_NO WHERE REC_NO = @REC_NO
	END
	ELSE
	BEGIN
		INSERT INTO TEACHER_SECTION
		SELECT @TEACHER_ID_NO,@SECTION_NO
	END
END
GO
DROP PROCEDURE PROC_STUDENT_INSERT
GO
CREATE PROCEDURE PROC_STUDENT_INSERT(@STUDENT_ID_NO VARCHAR(11),@NAME_SURNAME VARCHAR(50),@BIRTHDAY DATE,@EMAIL VARCHAR(20),@ZOOM_EMAIL VARCHAR(20),@ADDRES VARCHAR(250) )
AS
BEGIN
--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM STUDENT WHERE STUDENT_ID_NO = @STUDENT_ID_NO)
	BEGIN 
		UPDATE STUDENT SET NAME_SURNAME=@NAME_SURNAME,BIRTHDAY=@BIRTHDAY,EMAIL=@EMAIL,ZOOM_EMAIL=@ZOOM_EMAIL,ADDRES=@ADDRES WHERE STUDENT_ID_NO = @STUDENT_ID_NO
	END
	ELSE
	BEGIN
		INSERT INTO STUDENT
		SELECT @STUDENT_ID_NO,@NAME_SURNAME,@BIRTHDAY,@EMAIL,@ZOOM_EMAIL,@ADDRES
	END
END

GO

DROP PROCEDURE PROC_LESSON_INSERT
GO
CREATE PROCEDURE PROC_LESSON_INSERT(@LESSON_NO INT,@LESSON_NAME VARCHAR(50))
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM LESSON WHERE LESSON_NO = @LESSON_NO)
	BEGIN 
		UPDATE LESSON SET LESSON_NAME=@LESSON_NAME WHERE LESSON_NO = @LESSON_NO
	END
	ELSE
	BEGIN
		INSERT INTO LESSON
		SELECT @LESSON_NO,@LESSON_NAME
	END
END

GO

DROP PROCEDURE PROC_TEACHER_LESSON_INSERT
GO
CREATE PROCEDURE PROC_TEACHER_LESSON_INSERT(@REC_NO INT,@TEACHER_ID_NO VARCHAR(11),@LESSON_NO INT)
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM TEACHER_LESSON WHERE REC_NO = @REC_NO)
	BEGIN 
		UPDATE TEACHER_LESSON SET TEACHER_ID_NO=@TEACHER_ID_NO,LESSON_NO=@LESSON_NO WHERE REC_NO = @REC_NO
	END
	ELSE
	BEGIN
		INSERT INTO TEACHER_LESSON
		SELECT @TEACHER_ID_NO,@LESSON_NO
	END
END

GO

DROP PROCEDURE PROC_STUDENT_LESSON_INSERT
GO
CREATE PROCEDURE PROC_STUDENT_LESSON_INSERT(@REC_NO INT,@STUDENT_ID_NO VARCHAR(11),@LESSON_NO INT)
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM STUDENT_LESSON WHERE REC_NO = @REC_NO)
	BEGIN 
		UPDATE STUDENT_LESSON SET STUDENT_ID_NO=@STUDENT_ID_NO,LESSON_NO=@LESSON_NO WHERE REC_NO = @REC_NO
	END
	ELSE
	BEGIN
		INSERT INTO STUDENT_LESSON
		SELECT @STUDENT_ID_NO,@LESSON_NO
	END
END

GO

DROP PROCEDURE PROC_LESSON_TYPE_INSERT
GO
CREATE PROCEDURE PROC_LESSON_TYPE_INSERT(@TYPE_NO INT,@TTYPE_NAME VARCHAR(50))
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM LESSON_TYPE WHERE TYPE_NO = @TYPE_NO)
	BEGIN 
		UPDATE LESSON_TYPE SET TTYPE_NAME=@TTYPE_NAME WHERE TYPE_NO = @TYPE_NO
	END
	ELSE
	BEGIN
		INSERT INTO LESSON_TYPE
		SELECT @TYPE_NO,@TTYPE_NAME
	END
END

GO

DROP PROCEDURE PROC_SYLLABUS_INSERT
GO
CREATE PROCEDURE PROC_SYLLABUS_INSERT(@REC_NO INT,@LESSON_NO INT,@TYPE_NO INT,@DAY_NAME VARCHAR(20),@ZOOM_LINK VARCHAR(1000))
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM SYLLABUS WHERE REC_NO = @REC_NO)
	BEGIN 
		UPDATE SYLLABUS SET LESSON_NO=@LESSON_NO,TYPE_NO=@TYPE_NO,DAY_NAME=@DAY_NAME,ZOOM_LINK=@ZOOM_LINK WHERE REC_NO = @REC_NO
	END
	ELSE
	BEGIN
		INSERT INTO SYLLABUS
		SELECT @LESSON_NO,@TYPE_NO,@DAY_NAME,@ZOOM_LINK
	END
END

GO

DROP PROCEDURE PROC_EXAM_SCHEDULE_INSERT
GO
CREATE PROCEDURE PROC_EXAM_SCHEDULE_INSERT(@REC_NO INT,@LESSON_NO INT,@TYPE_NO INT,@DATES DATE)
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM EXAM_SCHEDULE WHERE REC_NO = @REC_NO)
	BEGIN 
		UPDATE EXAM_SCHEDULE SET LESSON_NO=@LESSON_NO,TYPE_NO=@TYPE_NO,DATES=@DATES WHERE REC_NO = @REC_NO
	END
	ELSE
	BEGIN
		INSERT INTO EXAM_SCHEDULE
		SELECT @LESSON_NO,@TYPE_NO,@DATES
	END
END

GO

DROP PROCEDURE PROC_COURSE_DOCUMENTS_INSERT
GO
CREATE PROCEDURE PROC_COURSE_DOCUMENTS_INSERT(@REC_NO INT,@LESSON_NO INT,@DATES DATE,@AUDIO_LINK VARCHAR(1000),@TEXT_LINK VARCHAR(1000),@VIDEO_LINK VARCHAR(1000))
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM COURSE_DOCUMENTS WHERE REC_NO = @REC_NO)
	BEGIN 
		UPDATE COURSE_DOCUMENTS SET LESSON_NO=@LESSON_NO,DATES=@DATES,AUDIO_LINK=@AUDIO_LINK,TEXT_LINK=@TEXT_LINK,VIDEO_LINK=@VIDEO_LINK  WHERE REC_NO = @REC_NO
	END
	ELSE
	BEGIN
		INSERT INTO COURSE_DOCUMENTS
		SELECT @LESSON_NO,@DATES,@AUDIO_LINK,@TEXT_LINK,@VIDEO_LINK
	END
END

GO

DROP PROCEDURE PROC_STUDENT_NOTES_INSERT
GO
CREATE PROCEDURE PROC_STUDENT_NOTES_INSERT(@REC_NO INT,@LESSON_NO INT,@STUDENT_ID_NO VARCHAR(11),@MIDTERM_EXAM FLOAT,@FINAL FLOAT)
AS
BEGIN
	--Primary alana göre kayýt varsa update deðilse insert iþlemi.
	IF EXISTS(SELECT TOP 1 * FROM STUDENT_NOTES WHERE REC_NO = @REC_NO)
	BEGIN 
		UPDATE STUDENT_NOTES SET LESSON_NO=@LESSON_NO,STUDENT_ID_NO=@STUDENT_ID_NO,MIDTERM_EXAM=@MIDTERM_EXAM,FINAL=@FINAL WHERE REC_NO = @REC_NO
	END
	ELSE
	BEGIN
		INSERT INTO STUDENT_NOTES
		SELECT @LESSON_NO,@STUDENT_ID_NO,@MIDTERM_EXAM,@FINAL
	END
END
GO
