CREATE DATABASE ONLINE_SCHOOL
GO
USE ONLINE_SCHOOL
GO

CREATE TABLE SECTION(
SECTION_NO INT PRIMARY KEY
,SECTION_NAME VARCHAR(50)
)
GO
CREATE TABLE TEACHER(
TEACHER_ID_NO VARCHAR(11) PRIMARY KEY
,NAME_SURNAME VARCHAR(50)
,BIRTHDAY DATE
,EMAIL VARCHAR(20)
,ZOOM_EMAIL VARCHAR(20)
,ADDRES VARCHAR(250)
)
GO
CREATE TABLE TEACHER_SECTION(
REC_NO INT IDENTITY(1,1) PRIMARY KEY
,TEACHER_ID_NO VARCHAR(11)
,SECTION_NO INT
,FOREIGN KEY (TEACHER_ID_NO) REFERENCES TEACHER(TEACHER_ID_NO)
,FOREIGN KEY (SECTION_NO) REFERENCES SECTION(SECTION_NO)
)
GO
CREATE TABLE STUDENT(
STUDENT_ID_NO VARCHAR(11) PRIMARY KEY
,NAME_SURNAME VARCHAR(50)
,BIRTHDAY DATE
,EMAIL VARCHAR(20)
,ZOOM_EMAIL VARCHAR(20)
,ADDRES VARCHAR(250)
)
GO
CREATE TABLE LESSON(
LESSON_NO INT PRIMARY KEY
,LESSON_NAME VARCHAR(50)
)
GO
CREATE TABLE TEACHER_LESSON(
REC_NO INT IDENTITY(1,1) PRIMARY KEY
,TEACHER_ID_NO VARCHAR(11)
,LESSON_NO INT
,FOREIGN KEY (TEACHER_ID_NO) REFERENCES TEACHER(TEACHER_ID_NO)
,FOREIGN KEY (LESSON_NO) REFERENCES LESSON(LESSON_NO)
)
GO
CREATE TABLE STUDENT_LESSON(
REC_NO INT IDENTITY(1,1) PRIMARY KEY
,STUDENT_ID_NO VARCHAR(11)
,LESSON_NO INT
,FOREIGN KEY (STUDENT_ID_NO) REFERENCES STUDENT(STUDENT_ID_NO)
,FOREIGN KEY (LESSON_NO) REFERENCES LESSON(LESSON_NO)
)
GO
CREATE TABLE LESSON_TYPE(
TYPE_NO INT PRIMARY KEY
,TTYPE_NAME VARCHAR(50)
)
GO
CREATE TABLE SYLLABUS(
REC_NO INT IDENTITY(1,1) PRIMARY KEY
,LESSON_NO INT
,TYPE_NO INT
,DAY_NAME VARCHAR(20)
,ZOOM_LINK VARCHAR(1000)
,FOREIGN KEY (TYPE_NO) REFERENCES LESSON_TYPE(TYPE_NO)
,FOREIGN KEY (LESSON_NO) REFERENCES LESSON(LESSON_NO)
)
GO
CREATE TABLE EXAM_SCHEDULE(
REC_NO INT IDENTITY(1,1) PRIMARY KEY
,LESSON_NO INT
,TYPE_NO INT
,DATES DATE
,FOREIGN KEY (TYPE_NO) REFERENCES LESSON_TYPE(TYPE_NO)
,FOREIGN KEY (LESSON_NO) REFERENCES LESSON(LESSON_NO)
)
GO
CREATE TABLE COURSE_DOCUMENTS(
REC_NO INT IDENTITY(1,1) PRIMARY KEY
,LESSON_NO INT
,DATES DATE
,AUDIO_LINK VARCHAR(1000)
,TEXT_LINK VARCHAR(1000)
,VIDEO_LINK VARCHAR(1000)
,FOREIGN KEY (LESSON_NO) REFERENCES LESSON(LESSON_NO)
)
GO
CREATE TABLE STUDENT_NOTES(
REC_NO INT IDENTITY(1,1) PRIMARY KEY
,LESSON_NO INT
,STUDENT_ID_NO VARCHAR(11)
,MIDTERM_EXAM FLOAT
,FINAL FLOAT
,FOREIGN KEY (LESSON_NO) REFERENCES LESSON(LESSON_NO)
,FOREIGN KEY (STUDENT_ID_NO) REFERENCES STUDENT(STUDENT_ID_NO)
)